# Generated by Django 4.1.4 on 2023-01-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_dealership', '0003_accessories_is_published_accessories_time_create_and_more'),
        ('supplier', '0002_founder_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='founder',
            options={'ordering': ['first_name'], 'verbose_name': 'Основатель', 'verbose_name_plural': 'Основатели'},
        ),
        migrations.AddField(
            model_name='founder',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='founder',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='founder',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='fanshops',
            field=models.ManyToManyField(related_name='supplier_fanshops', to='fan_dealership.fan_dealership'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
