# Generated by Django 4.1.4 on 2023-01-23 10:11

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaser',
            name='location',
            field=django_countries.fields.CountryField(default='Germany', max_length=2),
        ),
    ]
